version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16.1

    working_directory: ~/client

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

workflows:
  version: 2
  test:
    jobs:
      - build