/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function DonutModel({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model.gltf')
  return (
    <group ref={group}  dispose={null}>
      {/* <PerspectiveCamera
        makeDefault={false}
        far={64.99}
        near={0.01}
        fov={35}
        position={[-0.65, 0.76, -0.39]}
        rotation={[-2.11, -0.63, -2.37]}
      /> */}
      <mesh
        geometry={nodes.Torus.geometry}
        material={materials.Infinity}
        position={props.position}
        rotation={props.position}
        scale={0.08}
      />
    </group>
  )
}

useGLTF.preload('/model.gltf')
