INSERT INTO user_ratings (listing_id, rater_id, ratee_id, rating, comment)
VALUES
 (20, 2, 3, 5, 'Amazing service'),
 (2, 1, 13, 3, 'Unfortunately my coffee was not hot enough.'),
 (3, 14, 10, 4, 'Incredible painting skills.'),
 (17, 4, 1, 1, 'Booked and did not show up.'),
 (5, 5, 2, 2, 'Isabelle did not paint my deck very well.'),
 (6, 3, 7, 5, 'Fantastic service, food was delivered very quickly and my meal was fresh.'),
 (7, 7, 2, 4, 'I needed to pick up some supplies from Staples and Isabelle delivered everything I needed in a flash.'),
 (17, 2, 12, 4, 'Went all the way to Burlington to bring back some supplies from my favorite shop.'),
 (22, 1, 12, 1, 'Bad attitude'),
 (23, 3, 12, 2, 'Terrible - Didnt show'),
 (24, 4, 12, 5, 'I have nothing but great things to say about working for Tim'),
 (25, 5, 12, 5, 'He provided all the supplies and everything.'),
 (26, 6, 12, 4, 'Brought me out a snack and some drinks while I was doing the job. Would recommend!'),
 (9, 9, 11, 4, 'A fantastic job! Great cutomer support from beginning to end of the process. They are really informed and go the extra mile at every stage. I would recommend them unreservedly'),
 (10, 12, 11, 4, 'A fantastic organisation! Great cutomer support from beginning to end of the process. The team are really informed and go the extra mile at every stage. I would recommend them unreservedly'),
 (18, 11, 2, 4, 'Excellent customer service. (EN) was very friendly, patient and helpful in helping us find what we were looking for.'),
 (1, 12, 7, 4, 'Great customer service! The man I spoke with was very helpful in answering questions as well as helping in finding the best hotel for my husband and I.'),
 (13, 4, 14, 3, 'Job was done OK. I really wanted to give a higher rating.'),
 (17, 14, 10, 5, 'INCREDIBLE JOB. That is all.'),
 (15, 10, 6, 1, 'Worst job I have ever gotten done. The person was incredible rude.'),
 (20, 6, 10, 2, 'Bad customer service. Do not recommend, stay away!!!'),
 (8, 10, 4, 1, 'I had a terrible experience with this individual, they were talking on the phone the whole time and not very concentrated on their work.'),
 (8, 12, 13, 4, 'I am very happy with the phone that this person picked up for me.'),
 (2, 13, 9, 4, 'Thank you for the dumpling pick up!'),
 (1, 9, 1, 4, 'Good service.'),
 (1, 11, 1, 5, 'They did such a great job. Happy to hire again'),
 (2, 9, 2, 4, 'They did such a great job. Happy to hire again'),
 (3, 9, 3, 5, 'They did such a great job. Happy to hire again'),
 (4, 10, 1, 4, 'Excellent!'),
 (5, 10, 4, 5, 'Prompt and great work!'),
 (1, 10, 5, 4, 'Highly recommended!'),
 (2, 11, 6, 5, 'Good service.'),
 (3, 11, 7, 4, 'Great person! So helpful'),
 (4, 11, 8, 5, 'Amazing!'),
 (5, 8, 9, 3, 'Great experience working with them.'),
 (1, 8, 10, 2, 'They did the job, but then demanded more money! :( '),
 (2, 8, 11, 4, 'Great! Definitly work for them. You wont regret it'),
 (6, 11, 12, 5, 'Wonderful!'),
 (7, 12, 2, 5, 'They mowed my lawn and did an excellent job!'),
 (8, 13, 3, 5, 'Helped me move house! Fantastic work and quick!'),
 (9, 14, 4, 3, 'Okay to work for. They had high expectations for little pay'),
 (10, 11, 5, 1, 'Not cool'),
 (11, 12, 6, 3, 'Good experience, but not great'),
 (12, 13, 7, 5, 'Fantastic! They went above and beyond. You definitely want them for any job!'),
 (20, 2, 1, 5, 'Amazing service'),
 (2, 1, 2, 3, 'Unfortunately my coffee was not hot enough.'),
 (3, 14, 3, 4, 'Incredible painting skills.'),
 (17, 10, 4, 1, 'Booked and did not show up.'),
 (5, 8, 5, 2, 'They are awesome. So friendly!'),
 (6, 3, 6, 5, 'Fantastic service, food was delivered very quickly and my meal was fresh.'),
 (7, 7, 7, 4, 'I needed to pick up some supplies from Staples and Isabelle delivered everything I needed in a flash.'),
 (17, 2, 8, 4, 'Went all the way to Burlington to bring back some supplies from my favorite shop.'),
 (22, 1, 9, 1, 'Bad attitude'),
 (23, 3, 10, 2, 'Terrible - Didnt show'),
 (24, 4, 11, 5, 'I have nothing but great things to say about working for Tim'),
 (25, 5, 13, 5, 'He provided all the supplies and everything.'),
 (26, 6, 14, 4, 'Brought me out a snack and some drinks while I was doing the job. Would recommend!'),
 (9, 9, 12, 4, 'A fantastic job! Great cutomer support from beginning to end of the process. They are really informed and go the extra mile at every stage. I would recommend them unreservedly'),
 (18, 11, 2, 4, 'Excellent customer service. Was very friendly, patient and helpful in helping us find what we were looking for.'),
 (13, 4, 3, 3, 'Job was done OK. I really wanted to give a higher rating.'),
 (17, 14, 1, 5, 'INCREDIBLE JOB. That is all.'),
 (20, 6, 2, 2, 'Bad customer service. Do not recommend, stay away!!!'),
 (8, 12, 3, 4, 'I am very happy with the phone that this person picked up for me.'),
 (2, 13, 4, 4, 'Thank you for the dumpling pick up!'),
 (1, 9, 5, 4, 'Good service.'),
 (1, 11, 6, 5, 'They did such a great job. Happy to hire again'),
 (2, 9, 7, 4, 'They did such a great job. Happy to hire again'),
 (3, 9, 8, 5, 'They did such a great job. Happy to hire again'),
 (4, 10, 9, 4, 'Excellent!'),
 (5, 9, 10, 5, 'Prompt and great work!'),
 (1, 10, 1, 4, 'Highly recommended!'),
 (2, 11, 1, 5, 'Good service.'),
 (3, 11, 3, 4, 'Great person! So helpful'),
 (4, 11, 4, 5, 'Amazing!'),
 (5, 8, 5, 3, 'Great experience working with them.'),
 (1, 8, 6, 2, 'They did the job, but then demanded more money! :( '),
 (2, 8, 7, 4, 'Great! Definitly work for them. You wont regret it'),
 (6, 11, 8, 5, 'Wonderful!'),
 (7, 12, 9, 5, 'They mowed my lawn and did an excellent job!'),
 (8, 13, 10, 5, 'Helped me move house! Fantastic work and quick!'),
 (9, 14, 11, 3, 'Okay to work for. They had high expectations for little pay'),
 (11, 4, 12, 3, 'Good experience, but not great'),
 (12, 13, 3, 5, 'Fantastic! They went above and beyond. You definitely want them for any job!'),
 (3, 9, 1, 5, 'They did such a great job. Happy to hire again'),
 (4, 10, 2, 4, 'Excellent!'),
 (5, 10, 3, 5, 'Prompt and great work!'),
 (1, 10, 4, 4, 'Highly recommended!'),
 (2, 14, 5, 5, 'Good service.'),
 (3, 14, 6, 4, 'Great person! So helpful'),
 (4, 14, 7, 5, 'Amazing!'),
 (5, 14, 8, 3, 'Great experience working with them.'),
 (1, 8, 9, 2, 'They did the job, but then demanded more money! :( '),
 (2, 8, 10, 4, 'Great! Definitly work for them. You wont regret it'),
 (6, 13, 11, 5, 'Wonderful!'),
 (7, 12, 12, 5, 'They mowed my lawn and did an excellent job!'),
 (8, 9, 13, 5, 'Helped me move house! Fantastic work and quick!'),
 (9, 14, 1, 3, 'Okay to work for. They had high expectations for little pay'),
 (10, 11, 2, 1, 'Not cool'),
 (11, 12, 3, 3, 'Good experience, but not great'),
 (12, 13, 4, 5, 'Fantastic! They went above and beyond. You definitely want them for any job!');