INSERT INTO user_ratings (listing_id, rater_id, ratee_id, rating, comment)
VALUES
 (20, 2, 3, 5, "Amazing service, mowed my lawn very well!"),
 (2, 1, 13, 3, "Unfortunately my coffee was not hot enough."),
 (3, 14, 10, 4, "Incredible painting skills."),
 (17, 4, 1, 1, "Booked and did not show up."),
 (5, 5, 2, 2, "Isabelle did not paint my deck very well."),
 (6, 3, 7, 5, "Fantastic service, food was delivered very quickly and my meal was fresh."),
 (7, 7, 2, 4, "I needed to pick up some supplies from Staples and Isabelle delivered everything I needed in a flash."),
 (14, 2, 12, 4, "Went all the way to Burlington to bring back some supplies from my favorite shop."),
 (9, 9, 11, 4, "A fantastic job! Great cutomer support from beginning to end of the process. They are really informed and go the extra mile at every stage. I would recommend them unreservedly"),
 (10, 12, 11, 4, "A fantastic organisation! Great cutomer support from beginning to end of the process. The team are really informed and go the extra mile at every stage. I would recommend them unreservedly"),
 (18, 11, 2, 4, "Excellent customer service. (EN) was very friendly, patient and helpful in helping us find what we were looking for."),
 (1, 12, 7, 4, "Great customer service! The man I spoke with was very helpful in answering questions as well as helping in finding the best hotel for my husband and I."),
 (13, 4, 14, 3, "Job was done OK. I really wanted to give a higher rating."),
 (17, 14, 10, 5, "INCREDIBLE JOB. That is all."),
 (15, 10, 6, 1, "Worst job I've ever gotten done. The person was incredible rude."),
 (20, 6, 10, 2, "Bad customer service. Do not recommend, stay away!!!"),
 (8, 10, 4, 1, "I had a terrible experience with this individual, they were talking on the phone the whole time and not very concentrated on their work."),
 (8, 12, 13, 4, "I'm very happy with the phone that this person picked up for me. "),
 (2, 13, 9, 4, "Thank you for the dumpling pick up!"),
 (1, 9, 8, 3, "Good service, bad attitude.");