/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function CheckmarkModel({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[0, 5, 29]} scale={0.09}>
        <mesh geometry={nodes.Path.geometry} material={nodes.Path.material} />
        <mesh geometry={nodes.Path_1.geometry} material={nodes.Path_1.material} />
      </group>
      <PerspectiveCamera
        makeDefault={false}
        far={106.81}
        near={0.02}
        fov={35}
        position={[-0.34, 2.13, 0.55]}
        rotation={[-1.31, -0.01, -0.05]}
      />
    </group>
  )
}

useGLTF.preload('/model.gltf')
