/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Tube.geometry}
        material={materials.Bermuda}
        position={[0, 0, 0]}
        // rotation={[-0.91, Math.PI / 6, 1.71]}
        scale={0.002}
      />
    </group>
  )
}

useGLTF.preload('/model.gltf')
